from typing import Tuple, List

_states = [
    "Alabama",
    "Alaska",
    "_",
    "Arizona",
    "Arkansas",
    "California",
    "_",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "_",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "_",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "_",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

fips_codes: List[Tuple[int, str]] = list(
    filter(lambda i: i[1] != "_", enumerate(_states, start=1))
)

if __name__ == "__main__":
    assert len(fips_codes) == 51
